---
title: "p8105_hw6_sl4662"
author: "Siying Li "
date: "11/18/2019"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(modelr)
library(mgcv)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))
set.seed(1)
```

```{r}
birth_data = read.csv("./data/birthweight.csv")

lapply(birth_data, class)

birth_data = 
  birth_data %>% 
  mutate(
    babysex = factor(babysex, levels = c("1","2")),
    babysex = fct_recode(babysex, 
                           "male" = "1", 
                           "female" = "2"),
    frace = factor(frace, levels = c("1", "2", "3", "4", "8", "9")),
    frace = fct_recode(frace, 
                         "white" = "1", 
                         "black" = "2",
                         "asian" = "3",
                         "puerto_rican" = "4",
                         "other" = "8",
                         "unknown" = "9"),
    malform = factor(malform, levels = c("1","0")),
    malform = fct_recode(malform, 
                         "absent" = "0", 
                         "present" = "1"),
    mrace = factor(mrace, levels = c("1", "2", "3", "4", "8")),
    mrace = fct_recode(mrace, 
                         "white" = "1", 
                         "black" = "2",
                         "asian" = "3",
                         "puerto_rican" = "4",
                         "other" = "8")
         )
```

